### ISSUE TITLE
频繁接发数据出现异常

### ISSUE THREAD

**Issue by pasino1** [KibaAmor/knet#2]
异常出现如下：
<img width="623" alt="1635386800(1)" src="https://user-images.githubusercontent.com/43364859/139173750-bca514c5-f92c-4964-8f21-33c9e240f744.png">

**Comment by pasino1** [comment]
补充说明 used_size 会大于chunk的内容长度，多线程下 快速写入socket 会出现异常 当写入的中间加上控制台输出 就不会引发异常

**Comment by kibaamor** [comment]
1. used_size 会大于chunk的内容长度的问题？

    这个问题已经在新的提交中修复了。
    https://github.com/KibaAmor/knet/commit/27dd45362c484b03fa4e9e3525c5733287c7540b

2. 多线程下 快速写入socket 会出现异常

   目前，knet 设计的是可以使用不同的多线程来处理不同的 socket，从而提高吞吐。

   但是，同一个socket（对应着同一个 `conn` ）只能在同一个线程中读写。

   > PS: knet 能保证同一个 `conn` 的相关的回调，比如： `on_connected`, `on_disconnect`, `on_recv_data`, `on_timer` 等总是会在同一个线程中被调用，同时用户应该在相同的线程中使用 `conn` 上的接口，比如：`send_data`, `add_timer`, `disconnect` 等。
